### PR TITLE
Chinese localization update

### PR DESCRIPTION
**Pull request by nuthx**
Some of translation can't be determined due to no test of latest version. I'll fix if some translation is inappropriate.

### CODE REVIEW

**Comment by artem78** [comment]
> no test of latest version

You should asked me for this. There is pre-release version with last changes: [autoscreenshot_pre1.7.zip](https://github.com/artem78/AutoScreenshot/files/6434244/autoscreenshot_pre1.7.zip)

I saw questions marks instead of hieroglyphs:

**Comment by artem78** [comment]
> no test of latest version

Sorry, I forgot to gave you last build: [autoscreenshot_pre-1.7.zip](https://github.com/artem78/AutoScreenshot/files/6434550/autoscreenshot_pre-1.7.zip)

**Comment by artem78** [comment]
Tell me if there are no errors in translation and I will merge this pull request.

**Comment by nuthx** [comment]
Translation fixed.

**Comment by artem78** [comment]
Thanks.

**Pull request merged**
