### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by nuthx**

### CODE REVIEW

**Comment by artem78** [comment]
Thank you for contribution! Now I preparing for new release so there will be some more strings for translate. Also I want to add some changes for simplify adding new languages (now 2 languages hardcoded in the source code).

**Comment by artem78** [comment]
Hello.

Today I published [new release](https://github.com/artem78/AutoScreenshot/releases/tag/v1.6). Can you update your localization? You need to translate some new strings (Options, Help, UsedMonitor, AllMonitorsInfo, MonitorInfo, Primary, LocalizationAuthor) and add some additional info (see [wiki page](https://github.com/artem78/AutoScreenshot/wiki/UI-localization#specification)).

Moreover now new added languages become immediately available in the program.

**Comment by nuthx** [comment]
> Moreover now new added languages become immediately available in the program.

Fantastic feature, let me thranslate this weekend.

**Comment by artem78** [comment]
I fixed encoding in your file. You used UTF-8, but UCS2 (Unicode) required.

**Comment by artem78** [comment]
Hello, @nuthx.

I\`m preparing to make release of new version. Could you please update your Chinese localization?

Last changes located in [develop](https://github.com/artem78/AutoScreenshot/tree/develop) branch.

Thanks.

**Comment by artem78** [comment]
Here are the changes in English localization:
[en.ini.diff.txt](https://github.com/artem78/AutoScreenshot/files/6417461/en.ini.diff.txt)

**Pull request merged**
